[package]
name = "count"
version = "0.2.1"
authors = ["Julian Gehring"]
edition = "2018"

[dependencies]
hashbrown = {version = "0.7.2", features = ["rayon"]}
rayon = "1.3.0"
signal-hook = "0.1.15"
structopt = "0.3.14"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.4"

[profile.release]
lto = true
codegen-units = 1
